//
//  EntypoSymbol
//
//  Created by tichise on 2015/5/7 15/05/07.
//  Copyright (c) 2015 tichise. All rights reserved.
//

import UIKit

public class EntypoSymbol {
    
    var text:NSString = ""
    var mutableTextFontAttributes = [String : AnyObject]()
    
    public init(text:NSString, size:CGFloat) {
        self.text = text
        
        self.mutableTextFontAttributes = [String : AnyObject]()
        self.mutableTextFontAttributes[NSParagraphStyleAttributeName] = NSMutableParagraphStyle.defaultParagraphStyle().mutableCopy() as! NSMutableParagraphStyle
        
        self.mutableTextFontAttributes[NSFontAttributeName] = EntypoFont.fontOfSize(size)
    }
    
    public func addAttribute(attributeName:NSObject, value:AnyObject) {
        self.mutableTextFontAttributes[attributeName as! String] = value
    }
    
    public func imageWithSize(size:CGSize)->UIImage {
        UIGraphicsBeginImageContextWithOptions(size, false, 0)
        
        let textRect  = CGRectMake(0, 0, size.width, size.height)
        self.text.drawInRect(textRect, withAttributes: self.mutableTextFontAttributes)
        
        let image = UIGraphicsGetImageFromCurrentImageContext();
        
        UIGraphicsEndImageContext()
        
        return image
    }
}

private class FontLoader {
    class func loadFont(name: String) {
        
        let ttfPath = NSBundle(forClass:object_getClass(self)).pathForResource(name, ofType:"ttf")
        
        let fileHandle : NSFileHandle = NSFileHandle(forReadingAtPath: ttfPath!)!
        let data : NSData = fileHandle.readDataToEndOfFile()
        
        let provider = CGDataProviderCreateWithCFData(data)
        let font = CGFontCreateWithDataProvider(provider)!
        
        var error: Unmanaged<CFError>?
        if !CTFontManagerRegisterGraphicsFont(font, &error) {
            let errorDescription: CFStringRef = CFErrorCopyDescription(error!.takeUnretainedValue())
            let nsError = error!.takeUnretainedValue() as AnyObject as! NSError
            NSException(name: NSInternalInconsistencyException, reason: errorDescription as String, userInfo: [NSUnderlyingErrorKey: nsError]).raise()
        }
    }
}


public class EntypoFont {
    
    public class func fontOfSize(fontSize: CGFloat) -> UIFont {
        
        struct Static {
            static var onceToken : dispatch_once_t = 0
        }
        
        let name = "entypo"
        if (UIFont.fontNamesForFamilyName(name).count == 0) {
            dispatch_once(&Static.onceToken) {
                FontLoader.loadFont(name)
            }
        }
        
        return UIFont(name: name, size: fontSize)!
    }
}

public class EntypoIcon {
    
    public static let baidu = "\u{e749}"
    public static let houzz = "\u{e74a}"
    public static let windowsStore = "\u{e74b}"
    public static let googlePlay = "\u{e74c}"
    public static let appStore = "\u{e74d}"
    public static let mailWithCircle = "\u{e74e}"
    public static let medium = "\u{e74f}"
    public static let mediumWithCircle = "\u{e750}"
    public static let raftWithCircle = "\u{e751}"
    public static let raft = "\u{e752}"
    public static let qqWithCircle = "\u{e753}"
    public static let youkoWithCircle = "\u{e754}"
    public static let youko = "\u{e755}"
    public static let rainbow = "\u{e756}"
    public static let tripadvisor = "\u{e757}"
    public static let basecamp = "\u{e758}"
    public static let creativeCloud = "\u{e759}"
    public static let smashing = "\u{e75a}"
    public static let paypal = "\u{e75b}"
    public static let behance = "\u{e75c}"
    public static let mixi = "\u{e75d}"
    public static let soundcloud = "\u{e75e}"
    public static let picasa = "\u{e75f}"
    public static let googleDrive = "\u{e760}"
    public static let sinaWeibo = "\u{e761}"
    public static let renren = "\u{e762}"
    public static let swarm = "\u{e763}"
    public static let scribd = "\u{e764}"
    public static let foursquare = "\u{e765}"
    public static let flattr = "\u{e766}"
    public static let evernote = "\u{e767}"
    public static let slideshare = "\u{e768}"
    public static let googleHangouts = "\u{e769}"
    public static let qq = "\u{e76a}"
    public static let onedrive = "\u{e76b}"
    public static let dropbox = "\u{e76c}"
    public static let icloud = "\u{e76d}"
    public static let grooveshark = "\u{e76e}"
    public static let yelp = "\u{e76f}"
    public static let skypeWithCircle = "\u{e770}"
    public static let skype = "\u{e771}"
    public static let pxWithCircle = "\u{e772}"
    public static let px = "\u{e773}"
    public static let xingWithCircle = "\u{e774}"
    public static let xing = "\u{e775}"
    public static let vineWithCircle = "\u{e776}"
    public static let vine = "\u{e777}"
    public static let vkWithCircle = "\u{e778}"
    public static let vkAlternitive = "\u{e779}"
    public static let vk = "\u{e77a}"
    public static let spotifyWithCircle = "\u{e77b}"
    public static let spotify = "\u{e77c}"
    public static let rdioWithCircle = "\u{e77d}"
    public static let rdio = "\u{e77e}"
    public static let lastfm = "\u{e77f}"
    public static let lastfmWithCircle = "\u{e780}"
    public static let stumbleuponWithCircle = "\u{e781}"
    public static let stumbleupon = "\u{e782}"
    public static let dribbbleWithCircle = "\u{e783}"
    public static let dribbble = "\u{e784}"
    public static let linkedin = "\u{e785}"
    public static let linkedinWithCircle = "\u{e786}"
    public static let tumblrWithCircle = "\u{e787}"
    public static let tumblr = "\u{e788}"
    public static let pinterest = "\u{e789}"
    public static let pinterestWithCircle = "\u{e78a}"
    public static let instagramWithCircle = "\u{e78b}"
    public static let instagram = "\u{e78c}"
    public static let google = "\u{e79a}"
    public static let googleWithCircle = "\u{e799}"
    public static let facebookWithCircle = "\u{e798}"
    public static let facebook = "\u{e797}"
    public static let twitter = "\u{e796}"
    public static let twitterWithCircle = "\u{e795}"
    public static let vimeoWithCircle = "\u{e794}"
    public static let vimeo = "\u{e793}"
    public static let youtube = "\u{e792}"
    public static let youtubeWithCircle = "\u{e791}"
    public static let flickrWithCircle = "\u{e790}"
    public static let flickr = "\u{e78f}"
    public static let githubWithCircle = "\u{e78e}"
    public static let github = "\u{e78d}"
    public static let crop = "\u{e600}"
    public static let mousePointer = "\u{e601}"
    public static let fingerprint = "\u{e602}"
    public static let videoCamera = "\u{e603}"
    public static let bug = "\u{e604}"
    public static let tabletMobileCombo = "\u{e605}"
    public static let newsletter = "\u{e606}"
    public static let notificationsOff = "\u{e607}"
    public static let flower = "\u{e608}"
    public static let eyeWithLine = "\u{e609}"
    public static let merge = "\u{e60a}"
    public static let creativeCommonsPublicDomain = "\u{e60b}"
    public static let creativeCommonsRemix = "\u{e60c}"
    public static let creativeCommonsShare = "\u{e60d}"
    public static let creativeCommonsSharealike = "\u{e60e}"
    public static let creativeCommonsNoncommercialEu = "\u{e60f}"
    public static let creativeCommonsNoncommercialUs = "\u{e610}"
    public static let creativeCommonsNoderivs = "\u{e611}"
    public static let creativeCommonsAttribution = "\u{e612}"
    public static let creativeCommons = "\u{e613}"
    public static let warning = "\u{e614}"
    public static let documentLandscape = "\u{e615}"
    public static let classicComputer = "\u{e616}"
    public static let removeUser = "\u{e617}"
    public static let controllerFastBackward = "\u{e618}"
    public static let addToList = "\u{e619}"
    public static let dotsThreeHorizontal = "\u{e61a}"
    public static let dotsTwoHorizontal = "\u{e61b}"
    public static let dotSingle = "\u{e61c}"
    public static let dotsTwoVertical = "\u{e61d}"
    public static let dotsThreeVertical = "\u{e61e}"
    public static let selectArrows = "\u{e61f}"
    public static let arrowLongRight = "\u{e620}"
    public static let arrowLongUp = "\u{e621}"
    public static let arrowLongDown = "\u{e622}"
    public static let arrowLongLeft = "\u{e623}"
    public static let chevronWithCircleRight = "\u{e624}"
    public static let chevronWithCircleUp = "\u{e625}"
    public static let chevronWithCircleDown = "\u{e626}"
    public static let chevronWithCircleLeft = "\u{e627}"
    public static let chevronThinRight = "\u{e628}"
    public static let chevronThinUp = "\u{e629}"
    public static let chevronThinDown = "\u{e62a}"
    public static let chevronThinLeft = "\u{e62b}"
    public static let chevronSmallRight = "\u{e62c}"
    public static let chevronSmallUp = "\u{e62d}"
    public static let chevronSmallDown = "\u{e62e}"
    public static let chevronSmallLeft = "\u{e62f}"
    public static let chevronRight = "\u{e630}"
    public static let chevronUp = "\u{e631}"
    public static let chevronDown = "\u{e632}"
    public static let chevronLeft = "\u{e633}"
    public static let triangleRight = "\u{e634}"
    public static let triangleUp = "\u{e635}"
    public static let triangleDown = "\u{e636}"
    public static let triangleLeft = "\u{e637}"
    public static let arrowWithCircleRight = "\u{e638}"
    public static let arrowWithCircleUp = "\u{e639}"
    public static let arrowWithCircleDown = "\u{e63a}"
    public static let arrowWithCircleLeft = "\u{e63b}"
    public static let arrowRight = "\u{e63c}"
    public static let arrowUp = "\u{e63d}"
    public static let arrowDown = "\u{e63e}"
    public static let arrowLeft = "\u{e63f}"
    public static let arrowBoldRight = "\u{e640}"
    public static let arrowBoldUp = "\u{e641}"
    public static let arrowBoldDown = "\u{e642}"
    public static let arrowBoldLeft = "\u{e643}"
    public static let flowParallel = "\u{e644}"
    public static let flowLine = "\u{e645}"
    public static let flowTree = "\u{e646}"
    public static let flowBranch = "\u{e647}"
    public static let flowCascade = "\u{e648}"
    public static let soundMute = "\u{e649}"
    public static let sound = "\u{e64a}"
    public static let controllerVolume = "\u{e64b}"
    public static let resize100 = "\u{e64c}"
    public static let resizeFullScreen = "\u{e64d}"
    public static let controllerNext = "\u{e64e}"
    public static let controllerJumpToStart = "\u{e64f}"
    public static let controllerFastForward = "\u{e650}"
    public static let controllerStop = "\u{e651}"
    public static let controllerRecord = "\u{e652}"
    public static let controllerPaus = "\u{e653}"
    public static let controllerPlay = "\u{e654}"
    public static let openBook = "\u{e655}"
    public static let bookmarks = "\u{e656}"
    public static let bookmark = "\u{e657}"
    public static let layers = "\u{e658}"
    public static let uploadToCloud = "\u{e659}"
    public static let cloud = "\u{e65a}"
    public static let uninstall = "\u{e65b}"
    public static let install = "\u{e65c}"
    public static let save = "\u{e65d}"
    public static let download = "\u{e65e}"
    public static let upload = "\u{e65f}"
    public static let trash = "\u{e660}"
    public static let emojiFlirt = "\u{e661}"
    public static let archive = "\u{e662}"
    public static let timeSlot = "\u{e663}"
    public static let mask = "\u{e664}"
    public static let sportsClub = "\u{e665}"
    public static let folderVideo = "\u{e666}"
    public static let folderMusic = "\u{e667}"
    public static let folderImages = "\u{e668}"
    public static let folder = "\u{e669}"
    public static let music = "\u{e66a}"
    public static let video = "\u{e66b}"
    public static let images = "\u{e66c}"
    public static let imageInverted = "\u{e66d}"
    public static let image = "\u{e66e}"
    public static let copy = "\u{e66f}"
    public static let spreadsheet = "\u{e670}"
    public static let textDocumentInverted = "\u{e671}"
    public static let textDocument = "\u{e672}"
    public static let documents = "\u{e673}"
    public static let document = "\u{e674}"
    public static let menu = "\u{e675}"
    public static let grid = "\u{e676}"
    public static let list = "\u{e677}"
    public static let text = "\u{e678}"
    public static let unread = "\u{e679}"
    public static let emojiSad = "\u{e67a}"
    public static let emojiNeutral = "\u{e67b}"
    public static let emojiHappy = "\u{e67c}"
    public static let untag = "\u{e67d}"
    public static let tag = "\u{e67e}"
    public static let alignVerticalMiddle = "\u{e67f}"
    public static let alignHorizontalMiddle = "\u{e680}"
    public static let alignRight = "\u{e681}"
    public static let alignTop = "\u{e682}"
    public static let alignBottom = "\u{e683}"
    public static let alignLeft = "\u{e684}"
    public static let backInTime = "\u{e685}"
    public static let swap = "\u{e686}"
    public static let retweet = "\u{e687}"
    public static let loop = "\u{e688}"
    public static let levelUp = "\u{e689}"
    public static let levelDown = "\u{e68a}"
    public static let back = "\u{e68b}"
    public static let shuffle = "\u{e68c}"
    public static let circle = "\u{e68d}"
    public static let cw = "\u{e68e}"
    public static let ccw = "\u{e68f}"
    public static let cycle = "\u{e690}"
    public static let infoWithCircle = "\u{e691}"
    public static let helpWithCircle = "\u{e692}"
    public static let help = "\u{e693}"
    public static let info = "\u{e694}"
    public static let block = "\u{e695}"
    public static let erase = "\u{e696}"
    public static let plus = "\u{e697}"
    public static let minus = "\u{e698}"
    public static let circleWithCross = "\u{e699}"
    public static let circleWithPlus = "\u{e69a}"
    public static let circleWithMinus = "\u{e69b}"
    public static let squaredCross = "\u{e69c}"
    public static let squaredPlus = "\u{e69d}"
    public static let squaredMinus = "\u{e69e}"
    public static let cross = "\u{e69f}"
    public static let check = "\u{e6a0}"
    public static let switchIcon = "\u{e6a1}"
    public static let logOut = "\u{e6a2}"
    public static let login = "\u{e6a3}"
    public static let lockOpen = "\u{e6a4}"
    public static let lock = "\u{e6a5}"
    public static let circularGraph = "\u{e6a6}"
    public static let areaGraph = "\u{e6a7}"
    public static let barGraph = "\u{e6a8}"
    public static let pieChart = "\u{e6a9}"
    public static let lineGraph = "\u{e6aa}"
    public static let sweden = "\u{e6ab}"
    public static let water = "\u{e6ac}"
    public static let thermometer = "\u{e6ad}"
    public static let signal = "\u{e6ae}"
    public static let rss = "\u{e6af}"
    public static let ticket = "\u{e6b0}"
    public static let box = "\u{e6b1}"
    public static let database = "\u{e6b2}"
    public static let clipboard = "\u{e6b3}"
    public static let voicemail = "\u{e6b4}"
    public static let dialPad = "\u{e6b5}"
    public static let wallet = "\u{e6b6}"
    public static let shoppingBasket = "\u{e6b7}"
    public static let shoppingBag = "\u{e6b8}"
    public static let shoppingCart = "\u{e6b9}"
    public static let shop = "\u{e6ba}"
    public static let creditCard = "\u{e6bb}"
    public static let lightBulb = "\u{e6bc}"
    public static let infinity = "\u{e6bd}"
    public static let tv = "\u{e6be}"
    public static let code = "\u{e6bf}"
    public static let soundMix = "\u{e6c0}"
    public static let adjust = "\u{e6c1}"
    public static let lightUp = "\u{e6c2}"
    public static let lightDown = "\u{e6c3}"
    public static let progressEmpty = "\u{e6c4}"
    public static let progressOne = "\u{e6c5}"
    public static let progressTwo = "\u{e6c6}"
    public static let progressFull = "\u{e6c7}"
    public static let publish = "\u{e6c8}"
    public static let browser = "\u{e6c9}"
    public static let scissors = "\u{e6ca}"
    public static let eraser = "\u{e6cb}"
    public static let pencil = "\u{e6cc}"
    public static let flatBrush = "\u{e6cd}"
    public static let roundBrush = "\u{e6ce}"
    public static let keyboard = "\u{e6cf}"
    public static let radio = "\u{e6d0}"
    public static let globe = "\u{e6d1}"
    public static let trafficCone = "\u{e6d2}"
    public static let suitcase = "\u{e6d3}"
    public static let brush = "\u{e6d4}"
    public static let ruler = "\u{e6d5}"
    public static let labFlask = "\u{e6d6}"
    public static let rocket = "\u{e6d7}"
    public static let cup = "\u{e6d8}"
    public static let gameController = "\u{e6d9}"
    public static let drive = "\u{e6da}"
    public static let cake = "\u{e6db}"
    public static let magnet = "\u{e6dc}"
    public static let funnel = "\u{e6dd}"
    public static let bucket = "\u{e6de}"
    public static let battery = "\u{e6df}"
    public static let stopwatch = "\u{e6e0}"
    public static let key = "\u{e6e1}"
    public static let network = "\u{e6e2}"
    public static let language = "\u{e6e3}"
    public static let colours = "\u{e6e4}"
    public static let gauge = "\u{e6e5}"
    public static let tree = "\u{e6e6}"
    public static let hourGlass = "\u{e6e7}"
    public static let air = "\u{e6e8}"
    public static let briefcase = "\u{e6e9}"
    public static let bowl = "\u{e6ea}"
    public static let vinyl = "\u{e6eb}"
    public static let drop = "\u{e6ec}"
    public static let thunderCloud = "\u{e6ed}"
    public static let calendar = "\u{e6ee}"
    public static let flash = "\u{e6ef}"
    public static let mic = "\u{e6f0}"
    public static let clock = "\u{e6f1}"
    public static let hand = "\u{e6f2}"
    public static let credit = "\u{e6f3}"
    public static let eye = "\u{e6f4}"
    public static let lifebuoy = "\u{e6f5}"
    public static let aircraftLanding = "\u{e6f6}"
    public static let aircraftTakeOff = "\u{e6f7}"
    public static let shield = "\u{e6f8}"
    public static let aircraft = "\u{e6f9}"
    public static let news = "\u{e6fa}"
    public static let pin = "\u{e6fb}"
    public static let book = "\u{e6fc}"
    public static let blackboard = "\u{e6fd}"
    public static let graduationCap = "\u{e6fe}"
    public static let new = "\u{e6ff}"
    public static let medal = "\u{e700}"
    public static let priceRibbon = "\u{e701}"
    public static let clapperboard = "\u{e702}"
    public static let modernMic = "\u{e703}"
    public static let beamedNote = "\u{e704}"
    public static let note = "\u{e705}"
    public static let drink = "\u{e706}"
    public static let man = "\u{e707}"
    public static let leaf = "\u{e708}"
    public static let palette = "\u{e709}"
    public static let moon = "\u{e70a}"
    public static let awarenessRibbon = "\u{e70b}"
    public static let megaphone = "\u{e70c}"
    public static let camera = "\u{e70d}"
    public static let priceTag = "\u{e70e}"
    public static let powerPlug = "\u{e70f}"
    public static let trophy = "\u{e710}"
    public static let tools = "\u{e711}"
    public static let cog = "\u{e712}"
    public static let flag = "\u{e713}"
    public static let link = "\u{e714}"
    public static let bell = "\u{e715}"
    public static let print = "\u{e716}"
    public static let calculator = "\u{e717}"
    public static let flashlight = "\u{e718}"
    public static let magnifyingGlass = "\u{e719}"
    public static let popup = "\u{e71a}"
    public static let home = "\u{e71b}"
    public static let quote = "\u{e71c}"
    public static let typing = "\u{e71d}"
    public static let message = "\u{e71e}"
    public static let address = "\u{e71f}"
    public static let attachment = "\u{e720}"
    public static let chat = "\u{e721}"
    public static let compass = "\u{e722}"
    public static let direction = "\u{e723}"
    public static let edit = "\u{e724}"
    public static let email = "\u{e725}"
    public static let export = "\u{e726}"
    public static let feather = "\u{e727}"
    public static let forward = "\u{e728}"
    public static let hairCross = "\u{e729}"
    public static let heartOutlined = "\u{e72a}"
    public static let heart = "\u{e72b}"
    public static let inbox = "\u{e72c}"
    public static let landline = "\u{e72d}"
    public static let laptop = "\u{e72e}"
    public static let locationPin = "\u{e72f}"
    public static let location = "\u{e730}"
    public static let mail = "\u{e731}"
    public static let map = "\u{e732}"
    public static let mobile = "\u{e733}"
    public static let mouse = "\u{e734}"
    public static let newMessage = "\u{e735}"
    public static let notification = "\u{e736}"
    public static let oldMobile = "\u{e737}"
    public static let oldPhone = "\u{e738}"
    public static let paperPlane = "\u{e739}"
    public static let phone = "\u{e73a}"
    public static let replyAll = "\u{e73b}"
    public static let reply = "\u{e73c}"
    public static let shareAlternative = "\u{e73d}"
    public static let share = "\u{e73e}"
    public static let shareable = "\u{e73f}"
    public static let starOutlined = "\u{e740}"
    public static let star = "\u{e741}"
    public static let tablet = "\u{e742}"
    public static let thumbsDown = "\u{e743}"
    public static let thumbsUp = "\u{e744}"
    public static let user = "\u{e745}"
    public static let users = "\u{e746}"
    public static let vCard = "\u{e747}"
    public static let addUser = "\u{e748}"
}
